version: "3"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:3000"
    command: npm run dev
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: couchdb:3.2.0
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_NAME=${COUCHDB_NAME}
      - COUCHDB_SECRET=admin-secret
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
    ports:
      - "5984:5984"
    restart: unless-stopped
